
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import org.json.JSONObject;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Juan Pablo Guevara
 */
public class Calcular extends javax.swing.JFrame {

    
    /**
     * Creates new form Calcular
     */
    public Calcular() {
        initComponents();
        this.setLocationRelativeTo(null);
        //hacer consulta a la api
         this.getCurrencyFromApi();
        //asginar el valor a las divisas que queremos calcular
        
        
    }
     private static void getCurrencyFromApi() {
    try {
        URL url = new URL("https://mindicador.cl/api");
        HttpURLConnection con = (HttpURLConnection) url.openConnection();
        con.setRequestMethod("GET");

        int status = con.getResponseCode();

        BufferedReader in = new BufferedReader(
                new InputStreamReader(con.getInputStream()));
        String inputLine;
        StringBuffer content = new StringBuffer();
        while ((inputLine = in.readLine()) != null) {
            content.append(inputLine);
        }

        // Aquí puedes procesar los datos de la respuesta, por ejemplo:
        String json = content.toString();
        // Realizar la conversión a un objeto JSON, por ejemplo con la librería Jackson
        // ...
        JSONObject jsonObject = new JSONObject(json);
        System.out.println(jsonObject);
        double dolarValor = jsonObject.getJSONObject("dolar").getDouble("valor");
        double euroValor = jsonObject.getJSONObject("euro").getDouble("valor");
        double ufValor = jsonObject.getJSONObject("uf").getDouble("valor");

        System.out.println(dolarValor);
        System.out.println(euroValor);
        System.out.println(ufValor);
        // asignar el valor a txtcalc
        txtcalc.setText (Double.toString(dolarValor));
        txtcalc2.setText (Double.toString(euroValor));
        txtcalc3.setText (Double.toString(ufValor));
 

        in.close();
    } catch (MalformedURLException e) {
        e.printStackTrace();
    } catch (IOException e) {
        e.printStackTrace();
    }
}

    // Aquí puedes procesar los datos de la respuesta, por ejemplo:

    // Realizar la conversión a un objeto JSON, por ejemplo con la librería Jackson
    // ...


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtusp = new javax.swing.JTextField();
        txtusp2 = new javax.swing.JTextField();
        btnusp = new javax.swing.JButton();
        btnpusp2 = new javax.swing.JButton();
        txteurop = new javax.swing.JTextField();
        txteurop2 = new javax.swing.JTextField();
        btneurop = new javax.swing.JButton();
        btneurop2 = new javax.swing.JButton();
        txtcalc = new javax.swing.JTextField();
        txtcalc2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtufp = new javax.swing.JTextField();
        btnufp = new javax.swing.JButton();
        txtcalc3 = new javax.swing.JTextField();
        btnufp2 = new javax.swing.JButton();
        txtufp2 = new javax.swing.JTextField();
        btntodop = new javax.swing.JButton();
        btndivi = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculador de Divisas");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        jLabel1.setText("Calculador");

        txtusp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuspActionPerformed(evt);
            }
        });

        txtusp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusp2ActionPerformed(evt);
            }
        });

        btnusp.setText("Dolar(US) a Peso");
        btnusp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuspActionPerformed(evt);
            }
        });

        btnpusp2.setText("Peso a Dolar(US)");
        btnpusp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpusp2ActionPerformed(evt);
            }
        });

        btneurop.setText("Euro a Peso");
        btneurop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneuropActionPerformed(evt);
            }
        });

        btneurop2.setText("Peso a Euro");
        btneurop2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneurop2ActionPerformed(evt);
            }
        });

        txtcalc.setEditable(false);
        txtcalc.setToolTipText("");
        txtcalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalcActionPerformed(evt);
            }
        });

        txtcalc2.setEditable(false);
        txtcalc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcalc2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Valor");

        jLabel3.setText("Cantidad ");

        jLabel4.setText("Resultado");

        btnufp.setText("UF a Peso");
        btnufp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnufpActionPerformed(evt);
            }
        });

        txtcalc3.setEditable(false);

        btnufp2.setText("Peso a UF");
        btnufp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnufp2ActionPerformed(evt);
            }
        });

        btntodop.setText("Calcular todo a Peso");
        btntodop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntodopActionPerformed(evt);
            }
        });

        btndivi.setText("Calcular Divisas");
        btndivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndiviActionPerformed(evt);
            }
        });

        jButton6.setText("Limpiar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtufp, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(txteurop)
                                    .addComponent(txtusp))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnusp)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnufp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btneurop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(172, 172, 172))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtcalc, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtcalc2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtcalc3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btneurop2)
                                            .addComponent(btnpusp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(btnufp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(btntodop))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btndivi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6)
                    .addComponent(jLabel4)
                    .addComponent(txtusp2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txteurop2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtufp2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtusp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnusp)
                    .addComponent(btnpusp2)
                    .addComponent(txtcalc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txteurop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneurop)
                    .addComponent(txtcalc2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btneurop2)
                    .addComponent(txteurop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtufp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnufp)
                    .addComponent(txtcalc3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnufp2)
                    .addComponent(txtufp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntodop)
                    .addComponent(btndivi)
                    .addComponent(jButton6))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnuspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuspActionPerformed
        
        double dolarus,peso,valor;
          
        
      dolarus = Double.parseDouble(txtusp.getText());
      
      valor = Double.parseDouble(txtcalc.getText());
      peso =  dolarus*valor;
      txtusp2.setText(Double.toString(peso));
        
    }//GEN-LAST:event_btnuspActionPerformed

    private void txtcalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalcActionPerformed
    
        
    }//GEN-LAST:event_txtcalcActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void txtcalc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcalc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcalc2ActionPerformed

    private void btnpusp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpusp2ActionPerformed

            double dolarus,peso,valor;
            
      peso = Double.parseDouble(txtusp.getText());
      valor = Double.parseDouble(txtcalc.getText());
       dolarus= peso/valor;
      txtusp2.setText(Double.toString(dolarus));
    }//GEN-LAST:event_btnpusp2ActionPerformed

    private void btneuropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneuropActionPerformed

        double euro,peso,valor;
          
      euro = Double.parseDouble(txteurop.getText());
      valor = Double.parseDouble(txtcalc2.getText());
       peso= euro*valor;
      txteurop2.setText(Double.toString(peso));
    }//GEN-LAST:event_btneuropActionPerformed

    private void btneurop2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneurop2ActionPerformed
       
         double euro,peso,valor;
          
        
      peso = Double.parseDouble(txteurop.getText());
      valor = Double.parseDouble(txtcalc2.getText());
       euro= peso/valor;
      txteurop2.setText(Double.toString(euro));
    }//GEN-LAST:event_btneurop2ActionPerformed

    private void btnufpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnufpActionPerformed

    double uf,peso,valor;
          
        
      uf = Double.parseDouble(txtufp.getText());
      valor = Double.parseDouble(txtcalc3.getText());
      peso= uf*valor;
      txtufp2.setText(Double.toString(peso));
    
    }//GEN-LAST:event_btnufpActionPerformed

    private void btnufp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnufp2ActionPerformed

        double uf,peso,valor;
          
      peso = Double.parseDouble(txtufp.getText());
      valor = Double.parseDouble(txtcalc3.getText());
       uf= peso/valor;
      txtufp2.setText(Double.toString(uf));
    }//GEN-LAST:event_btnufp2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        txtusp.setText("");
        txtusp2.setText("");
        txteurop.setText("");
        txteurop2.setText("");
        txtufp.setText("");
        txtufp2.setText("");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btntodopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntodopActionPerformed

double dolarus,euro,uf,peso,peso2,peso3,valor,valor2,valor3;
          
        
      peso = Double.parseDouble(txtusp.getText());
      peso2 = Double.parseDouble(txteurop.getText());
      peso3 = Double.parseDouble(txtufp.getText());
      valor = Double.parseDouble(txtcalc.getText());
      valor2 = Double.parseDouble(txtcalc2.getText());
      valor3 = Double.parseDouble(txtcalc3.getText());
       dolarus= peso/valor;
       euro= peso2/valor2;
       uf = peso3/valor3;
      txtusp2.setText(Double.toString(dolarus));
      txteurop2.setText(Double.toString(euro));
      txtufp2.setText(Double.toString(uf));

        
    }//GEN-LAST:event_btntodopActionPerformed

    private void btndiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndiviActionPerformed


double dolarus,euro,uf,peso,peso2,peso3,valor,valor2,valor3;
          
        
      dolarus = Double.parseDouble(txtusp.getText());
      euro = Double.parseDouble(txteurop.getText());
      uf = Double.parseDouble(txtufp.getText());
      valor = Double.parseDouble(txtcalc.getText());
      valor2 = Double.parseDouble(txtcalc2.getText());
      valor3 = Double.parseDouble(txtcalc3.getText());
       peso= dolarus*valor;
       peso2= euro*valor2;
       peso3= uf*valor3;
      txtusp2.setText(Double.toString(peso));
      txteurop2.setText(Double.toString(peso2));
      txtufp2.setText(Double.toString(peso3));
    }//GEN-LAST:event_btndiviActionPerformed

    private void txtusp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusp2ActionPerformed

    private void txtuspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calcular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calcular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndivi;
    private javax.swing.JButton btneurop;
    private javax.swing.JButton btneurop2;
    private javax.swing.JButton btnpusp2;
    private javax.swing.JButton btntodop;
    private javax.swing.JButton btnufp;
    private javax.swing.JButton btnufp2;
    private javax.swing.JButton btnusp;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private static javax.swing.JTextField txtcalc;
    private static javax.swing.JTextField txtcalc2;
    private static javax.swing.JTextField txtcalc3;
    private javax.swing.JTextField txteurop;
    private javax.swing.JTextField txteurop2;
    private javax.swing.JTextField txtufp;
    private javax.swing.JTextField txtufp2;
    private javax.swing.JTextField txtusp;
    private javax.swing.JTextField txtusp2;
    // End of variables declaration//GEN-END:variables
}
